### ISSUE TITLE
Change the EmailConfirm boolean in database

### ISSUE THREAD

**Issue by netrunner1987** [wenhx/BlazorWebAssemblyWithIdentity#1]
I had to load up DB Browser for SQLite, and was able to see that I was able to create a user.  I set the EmailConfirmed to true.  I was still not able to login.  Learning with you.  Oh, just realized.. code is till being written...lol my bad.

**Comment by wenhx** [comment]
Hey, thanks for testing out the project and giving me your thoughts! Sorry to hear that you were having trouble logging in. I'm still working on the code, but I'm happy to say that the user login function is now up and running. You can download the updated code and check it out for yourself. Let me know if you have any other questions or feedback, and thanks for your interest in the project!
