### ISSUE TITLE
Will this project stay in SQLite or move on the MSSQL?

### ISSUE THREAD

**Issue by netrunner1987** [wenhx/BlazorWebAssemblyWithIdentity#2]
I'm a big user of MSSQL, so that is why I asked.  Thanks.

**Comment by wenhx** [comment]
Yes, you can easily switch from SQLite to MSSQL by modifying the code https://github.com/wenhx/BlazorWebAssemblyWithIdentity/blob/88dc677753cf5af93ed03a7c6a931b63d13a915e/src/Server/Program.cs#L22 as follows:
```
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(connectionString));
```
SQLite was chosen for its simplicity and suitability for a demo project, but MSSQL is the recommended database option for ASP.NET CORE Identity and is therefore the default choice. To switch to MSSQL, you will need to install the Microsoft.EntityFrameworkCore.SqlServer package first.
